const mongoose = require('mongoose');

const { connectDB, disconnectDB } = require('../config/db');
const PasswordResetRateLimit = require('../modules/auth/models/passwordResetRateLimit.model');
const PasswordResetToken = require('../modules/auth/models/passwordResetToken.model');
const PhoneVerification = require('../modules/auth/models/phoneVerification.model');
const RefreshToken = require('../modules/auth/models/refreshToken.model');
const AuditLog = require('../modules/audit-logs/auditLog.model');
const BookingServiceStep = require('../modules/booking-service-steps/bookingServiceStep.model');
const BookingWaitlist = require('../modules/booking-waitlists/bookingWaitlist.model');
const Booking = require('../modules/bookings/booking.model');
const Garage = require('../modules/garages/garage.model');
const CustomerLoyalty = require('../modules/loyalty/customerLoyalty.model');
const LoyaltyRedeemRule = require('../modules/loyalty/loyaltyRedeemRule.model');
const PointTransaction = require('../modules/loyalty/pointTransaction.model');
const TierRule = require('../modules/loyalty/tierRule.model');
const Notification = require('../modules/notifications/notification.model');
const PaymentTransaction = require('../modules/payments/paymentTransaction.model');
const PromotionUsage = require('../modules/promotion-usages/promotionUsage.model');
const Promotion = require('../modules/promotions/promotion.model');
const ServicePackage = require('../modules/service-packages/servicePackage.model');
const StaffProfile = require('../modules/staff-profiles/staffProfile.model');
const Survey = require('../modules/surveys/survey.model');
const SurveyResponse = require('../modules/surveys/surveyResponse.model');
const ResearchReport = require('../modules/research/researchReport.model');
const Upload = require('../modules/uploads/upload.model');
const User = require('../modules/users/user.model');
const VehicleInspection = require('../modules/vehicle-inspections/vehicleInspection.model');
const Vehicle = require('../modules/vehicles/vehicle.model');
const WashBay = require('../modules/wash-bays/washBay.model');
const WashHistory = require('../modules/wash-histories/washHistory.model');

const resetTargets = Object.freeze([
    { group: 'Runtime upload', model: Upload, seed: '-', note: 'Uploaded file metadata' },
    { group: 'Runtime audit', model: AuditLog, seed: '-', note: 'Generated by audited app events' },
    { group: 'Runtime research', model: ResearchReport, seed: '-', note: 'Admin research reports and snapshots' },
    { group: 'Runtime survey', model: SurveyResponse, seed: '-', note: 'Customer survey responses' },
    { group: 'Runtime survey', model: Survey, seed: '-', note: 'Admin-created surveys' },
    { group: 'Runtime booking', model: BookingServiceStep, seed: '-', note: 'Generated when service starts' },
    { group: 'Runtime booking', model: VehicleInspection, seed: '-', note: 'Generated from inspection flow' },
    { group: 'Runtime booking', model: PaymentTransaction, seed: '-', note: 'Generated from payment flow' },
    { group: 'Runtime booking', model: PromotionUsage, seed: '-', note: 'Generated from paid booking' },
    { group: 'Runtime booking', model: PointTransaction, seed: '-', note: 'Generated from loyalty flow' },
    { group: 'Runtime booking', model: WashHistory, seed: '-', note: 'Generated after completed paid booking' },
    { group: 'Runtime booking', model: Notification, seed: '-', note: 'Generated by app events' },
    { group: 'Runtime booking', model: BookingWaitlist, seed: '-', note: 'Customer waitlist entries and offers' },
    { group: 'Runtime booking', model: Booking, seed: '-', note: 'Customer and walk-in bookings' },
    { group: 'Auth transient', model: RefreshToken, seed: '-', note: 'Login sessions' },
    { group: 'Auth transient', model: PhoneVerification, seed: '-', note: 'Phone OTP challenges and rate limits' },
    { group: 'Auth transient', model: PasswordResetToken, seed: '-', note: 'Password reset tokens' },
    { group: 'Auth transient', model: PasswordResetRateLimit, seed: '-', note: 'Password reset rate limits' },
    { group: 'Seed data', model: CustomerLoyalty, seed: '-', note: 'Recreated by usage if needed' },
    { group: 'Seed data', model: StaffProfile, seed: 'seedStaffProfile.js', note: 'Depends on users and garages' },
    { group: 'Seed data', model: WashBay, seed: 'seedWashBay.js', note: 'Depends on garages' },
    { group: 'Seed data', model: Vehicle, seed: 'seedVehicle.js', note: 'Depends on customer users' },
    { group: 'Seed data', model: Promotion, seed: '-', note: 'Admin-created promotions' },
    { group: 'Seed data', model: ServicePackage, seed: 'seedServicePackage.js', note: 'Global service catalog' },
    { group: 'Seed data', model: LoyaltyRedeemRule, seed: 'seedLoyaltyRedeemRule.js', note: 'Loyalty redeem config' },
    { group: 'Seed data', model: TierRule, seed: 'seedTierRule.js', note: 'Loyalty tier config' },
    { group: 'Seed data', model: Garage, seed: 'seedGarage.js', note: 'Demo garages' },
    { group: 'Seed data', model: User, seed: 'seedUser.js', note: 'Admin, staff, customers' },
]);

const toResetTable = () => resetTargets.map((target, index) => ({
    order: index + 1,
    group: target.group,
    collection: target.model.collection.name,
    seed: target.seed,
    note: target.note,
}));

const isProductionTarget = () => {
    const dbName = mongoose.connection.name || process.env.MONGODB_DB_NAME || '';
    const nodeEnv = process.env.NODE_ENV || '';

    return nodeEnv.toLowerCase() === 'production' || /prod|production/i.test(dbName);
};

const resetDatabase = async ({ dryRun = process.argv.includes('--dry-run') } = {}) => {
    const dbName = mongoose.connection.name || process.env.MONGODB_DB_NAME || 'wdp301_project';
    const forceProduction = process.argv.includes('--force-production');

    if (isProductionTarget() && !forceProduction) {
        throw new Error('Database reset is blocked for production target. Use --force-production only when you are certain.');
    }

    const table = toResetTable();

    console.log(`Reset target database: ${dbName}`);
    console.table(table);

    if (dryRun) {
        console.log('Dry run completed. No data was deleted.');

        return {
            dry_run: true,
            table,
            deleted: [],
        };
    }

    const deleted = [];

    for (const target of resetTargets) {
        const collection = target.model.collection.name;
        const result = await target.model.deleteMany({});
        const deletedCount = result.deletedCount || 0;

        deleted.push({
            collection,
            deleted_count: deletedCount,
        });
        console.log(`Reset collection ${collection}: deleted ${deletedCount}`);
    }

    console.table(deleted);
    console.log('Database reset completed');

    return {
        dry_run: false,
        table,
        deleted,
    };
};

const run = async () => {
    let exitCode = 0;

    try {
        require('dotenv').config();
        await connectDB();
        await resetDatabase();
    } catch (error) {
        console.error('Database reset failed:', error);
        exitCode = 1;
    } finally {
        await disconnectDB();
        process.exitCode = exitCode;
    }
};

if (require.main === module) {
    run();
}

module.exports = {
    resetDatabase,
    resetTargets,
    toResetTable,
};
