const {
    PAYMENT_TRANSACTION_STATUS,
} = require('../shared/constants/payment.constant');
const {
    PROMOTION_USAGE_STATUS,
} = require('../shared/constants/promotion.constant');

const PROMOTION_USAGE_TARGETS = Object.freeze({
    CARCOMBO100: Object.freeze({
        [PROMOTION_USAGE_STATUS.CONSUMED]: 1,
        [PROMOTION_USAGE_STATUS.RESERVED]: 0,
        [PROMOTION_USAGE_STATUS.RELEASED]: 0,
    }),
    WALKIN30: Object.freeze({
        [PROMOTION_USAGE_STATUS.CONSUMED]: 2,
        [PROMOTION_USAGE_STATUS.RESERVED]: 0,
        [PROMOTION_USAGE_STATUS.RELEASED]: 0,
    }),
    PLATINUM20: Object.freeze({
        [PROMOTION_USAGE_STATUS.CONSUMED]: 1,
        [PROMOTION_USAGE_STATUS.RESERVED]: 1,
        [PROMOTION_USAGE_STATUS.RELEASED]: 0,
    }),
    GOLD15: Object.freeze({
        [PROMOTION_USAGE_STATUS.CONSUMED]: 6,
        [PROMOTION_USAGE_STATUS.RESERVED]: 2,
        [PROMOTION_USAGE_STATUS.RELEASED]: 0,
    }),
    SILVER10: Object.freeze({
        [PROMOTION_USAGE_STATUS.CONSUMED]: 8,
        [PROMOTION_USAGE_STATUS.RESERVED]: 3,
        [PROMOTION_USAGE_STATUS.RELEASED]: 0,
    }),
    MOTORBIKE10: Object.freeze({
        [PROMOTION_USAGE_STATUS.CONSUMED]: 8,
        [PROMOTION_USAGE_STATUS.RESERVED]: 1,
        [PROMOTION_USAGE_STATUS.RELEASED]: 0,
    }),
    MEMBER5: Object.freeze({
        [PROMOTION_USAGE_STATUS.CONSUMED]: 14,
        [PROMOTION_USAGE_STATUS.RESERVED]: 5,
        [PROMOTION_USAGE_STATUS.RELEASED]: 4,
    }),
    GRANDOPENING15: Object.freeze({
        [PROMOTION_USAGE_STATUS.CONSUMED]: 20,
        [PROMOTION_USAGE_STATUS.RESERVED]: 0,
        [PROMOTION_USAGE_STATUS.RELEASED]: 4,
    }),
});

const PAYMENT_STATUS_TARGETS = Object.freeze({
    [PAYMENT_TRANSACTION_STATUS.PAID]: 125,
    [PAYMENT_TRANSACTION_STATUS.EXPIRED]: 6,
    [PAYMENT_TRANSACTION_STATUS.FAILED]: 2,
    [PAYMENT_TRANSACTION_STATUS.CANCELED]: 4,
});

const PROMOTION_USAGE_TOTALS = Object.freeze({
    [PROMOTION_USAGE_STATUS.CONSUMED]: 60,
    [PROMOTION_USAGE_STATUS.RESERVED]: 12,
    [PROMOTION_USAGE_STATUS.RELEASED]: 8,
});

const PAYMENT_TRANSACTION_TOTAL = Object.values(
    PAYMENT_STATUS_TARGETS
).reduce((total, value) => total + value, 0);

const PROMOTION_USAGE_TOTAL = Object.values(
    PROMOTION_USAGE_TOTALS
).reduce((total, value) => total + value, 0);

const NO_USAGE_PROMOTION_CODES = Object.freeze([
    'EVWASH12',
    'WASH15_PAUSED',
]);

module.exports = {
    PROMOTION_USAGE_TARGETS,
    PROMOTION_USAGE_TOTALS,
    PROMOTION_USAGE_TOTAL,
    PAYMENT_STATUS_TARGETS,
    PAYMENT_TRANSACTION_TOTAL,
    NO_USAGE_PROMOTION_CODES,
};
