const {
    BOOKING_INCIDENT_TYPES,
    BOOKING_INCIDENT_STATUS,
    BOOKING_INCIDENT_DECISIONS,
} = require('../shared/constants/bookingIncident.constant');
const {
    CUSTOMER_VOUCHER_TYPES,
    CUSTOMER_VOUCHER_STATUS,
} = require('../shared/constants/customerVoucher.constant');
const {
    CUSTOMER_CASE_CATEGORIES,
    CUSTOMER_CASE_STATUSES,
    CUSTOMER_CASE_TECHNICAL_ASSESSMENT_STATUSES,
    CUSTOMER_CASE_RESOLUTION_STATUSES,
    CUSTOMER_CASE_REFUND_STATUSES,
} = require('../shared/constants/customerCase.constant');

const INCIDENT_TARGETS = Object.freeze({
    total: 10,
    by_type: Object.freeze({
        [BOOKING_INCIDENT_TYPES.WASH_BAY_FAILURE]: 4,
        [BOOKING_INCIDENT_TYPES.STAFF_UNAVAILABLE]: 4,
        [BOOKING_INCIDENT_TYPES.OTHER_GARAGE_INCIDENT]: 2,
    }),
    by_status: Object.freeze({
        [BOOKING_INCIDENT_STATUS.RESOLVED]: 9,
        [BOOKING_INCIDENT_STATUS.AWAITING_CUSTOMER_DECISION]: 1,
    }),
    by_decision: Object.freeze({
        [BOOKING_INCIDENT_DECISIONS.REASSIGN_AND_CONTINUE]: 3,
        [BOOKING_INCIDENT_DECISIONS.RESCHEDULE_NEAREST]: 2,
        [BOOKING_INCIDENT_DECISIONS.RESCHEDULE_CUSTOM]: 2,
        [BOOKING_INCIDENT_DECISIONS.CANCEL_BY_GARAGE]: 2,
    }),
    per_garage: 2,
});

const VOUCHER_TARGETS = Object.freeze({
    total: 12,
    by_type: Object.freeze({
        [CUSTOMER_VOUCHER_TYPES.FIXED_AMOUNT]: 6,
        [CUSTOMER_VOUCHER_TYPES.PERCENTAGE]: 4,
        [CUSTOMER_VOUCHER_TYPES.FREE_SERVICE]: 2,
    }),
    by_status: Object.freeze({
        [CUSTOMER_VOUCHER_STATUS.ISSUED]: 3,
        [CUSTOMER_VOUCHER_STATUS.PENDING_APPROVAL]: 2,
        [CUSTOMER_VOUCHER_STATUS.RESERVED]: 2,
        [CUSTOMER_VOUCHER_STATUS.USED]: 2,
        [CUSTOMER_VOUCHER_STATUS.EXPIRED]: 2,
        [CUSTOMER_VOUCHER_STATUS.REVOKED]: 1,
    }),
    by_source: Object.freeze({
        INCIDENT: 8,
        CUSTOMER_CASE: 4,
    }),
});

const CUSTOMER_CASE_TARGETS = Object.freeze({
    total: 18,
    registered: 15,
    walk_in: 3,
    by_garage: Object.freeze([4, 4, 4, 3, 3]),
    by_status: Object.freeze({
        [CUSTOMER_CASE_STATUSES.SUBMITTED]: 3,
        [CUSTOMER_CASE_STATUSES.ACKNOWLEDGED]: 3,
        [CUSTOMER_CASE_STATUSES.INVESTIGATING]: 5,
        [CUSTOMER_CASE_STATUSES.RESOLVED]: 4,
        [CUSTOMER_CASE_STATUSES.CLOSED]: 3,
    }),
    by_category: Object.freeze({
        [CUSTOMER_CASE_CATEGORIES.SERVICE_QUALITY]: 5,
        [CUSTOMER_CASE_CATEGORIES.VEHICLE_DAMAGE]: 4,
        [CUSTOMER_CASE_CATEGORIES.SERVICE_INCOMPLETE]: 3,
        [CUSTOMER_CASE_CATEGORIES.BILLING_PAYMENT]: 2,
        [CUSTOMER_CASE_CATEGORIES.MISSING_PROPERTY]: 1,
        [CUSTOMER_CASE_CATEGORIES.STAFF_CONDUCT]: 1,
        [CUSTOMER_CASE_CATEGORIES.SAFETY_CONCERN]: 1,
        [CUSTOMER_CASE_CATEGORIES.OTHER]: 1,
    }),
    by_source: Object.freeze({
        AFTER_HANDOVER: 17,
        HANDOVER: 1,
    }),
    reopened: 1,
    sla_escalated: 2,
});

const CUSTOMER_CASE_CATEGORY_SEQUENCE = Object.freeze([
    CUSTOMER_CASE_CATEGORIES.VEHICLE_DAMAGE,
    CUSTOMER_CASE_CATEGORIES.SERVICE_QUALITY,
    CUSTOMER_CASE_CATEGORIES.BILLING_PAYMENT,
    CUSTOMER_CASE_CATEGORIES.VEHICLE_DAMAGE,
    CUSTOMER_CASE_CATEGORIES.SERVICE_INCOMPLETE,
    CUSTOMER_CASE_CATEGORIES.MISSING_PROPERTY,
    CUSTOMER_CASE_CATEGORIES.STAFF_CONDUCT,
    CUSTOMER_CASE_CATEGORIES.SERVICE_QUALITY,
    CUSTOMER_CASE_CATEGORIES.SERVICE_INCOMPLETE,
    CUSTOMER_CASE_CATEGORIES.VEHICLE_DAMAGE,
    CUSTOMER_CASE_CATEGORIES.BILLING_PAYMENT,
    CUSTOMER_CASE_CATEGORIES.OTHER,
    CUSTOMER_CASE_CATEGORIES.SERVICE_QUALITY,
    CUSTOMER_CASE_CATEGORIES.SERVICE_INCOMPLETE,
    CUSTOMER_CASE_CATEGORIES.VEHICLE_DAMAGE,
    CUSTOMER_CASE_CATEGORIES.SERVICE_QUALITY,
    CUSTOMER_CASE_CATEGORIES.SERVICE_QUALITY,
    CUSTOMER_CASE_CATEGORIES.SAFETY_CONCERN,
]);

const CUSTOMER_CASE_STATUS_SEQUENCE = Object.freeze([
    CUSTOMER_CASE_STATUSES.CLOSED,
    CUSTOMER_CASE_STATUSES.CLOSED,
    CUSTOMER_CASE_STATUSES.CLOSED,
    CUSTOMER_CASE_STATUSES.RESOLVED,
    CUSTOMER_CASE_STATUSES.RESOLVED,
    CUSTOMER_CASE_STATUSES.RESOLVED,
    CUSTOMER_CASE_STATUSES.RESOLVED,
    CUSTOMER_CASE_STATUSES.INVESTIGATING,
    CUSTOMER_CASE_STATUSES.INVESTIGATING,
    CUSTOMER_CASE_STATUSES.INVESTIGATING,
    CUSTOMER_CASE_STATUSES.INVESTIGATING,
    CUSTOMER_CASE_STATUSES.INVESTIGATING,
    CUSTOMER_CASE_STATUSES.ACKNOWLEDGED,
    CUSTOMER_CASE_STATUSES.ACKNOWLEDGED,
    CUSTOMER_CASE_STATUSES.ACKNOWLEDGED,
    CUSTOMER_CASE_STATUSES.SUBMITTED,
    CUSTOMER_CASE_STATUSES.SUBMITTED,
    CUSTOMER_CASE_STATUSES.SUBMITTED,
]);

const CUSTOMER_CASE_DEPENDENT_TARGETS = Object.freeze({
    messages: 30,
    technical_assessments: 10,
    assessment_statuses: Object.freeze({
        [CUSTOMER_CASE_TECHNICAL_ASSESSMENT_STATUSES.ASSIGNED]: 2,
        [CUSTOMER_CASE_TECHNICAL_ASSESSMENT_STATUSES.IN_PROGRESS]: 2,
        [CUSTOMER_CASE_TECHNICAL_ASSESSMENT_STATUSES.SUBMITTED]: 6,
    }),
    resolutions: 12,
    resolution_statuses: Object.freeze({
        [CUSTOMER_CASE_RESOLUTION_STATUSES.APPLIED]: 8,
        [CUSTOMER_CASE_RESOLUTION_STATUSES.PROPOSED]: 1,
        [CUSTOMER_CASE_RESOLUTION_STATUSES.CUSTOMER_ACCEPTED]: 1,
        [CUSTOMER_CASE_RESOLUTION_STATUSES.CUSTOMER_REJECTED]: 1,
        [CUSTOMER_CASE_RESOLUTION_STATUSES.SUPERSEDED]: 1,
    }),
    refunds: 4,
    refund_statuses: Object.freeze({
        [CUSTOMER_CASE_REFUND_STATUSES.COMPLETED]: 2,
        [CUSTOMER_CASE_REFUND_STATUSES.PROCESSING]: 1,
        [CUSTOMER_CASE_REFUND_STATUSES.FAILED]: 1,
    }),
});

module.exports = {
    INCIDENT_TARGETS,
    VOUCHER_TARGETS,
    CUSTOMER_CASE_TARGETS,
    CUSTOMER_CASE_CATEGORY_SEQUENCE,
    CUSTOMER_CASE_STATUS_SEQUENCE,
    CUSTOMER_CASE_DEPENDENT_TARGETS,
};
